# Generated by Django 3.0.5 on 2020-04-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20200425_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Burger',
            new_name='Hamburguesa',
        ),
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Ingrediente',
        ),
    ]
