# Generated by Django 3.0.5 on 2020-04-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_auto_20200425_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(to='postings.Ingrediente'),
        ),
    ]
