# Generated by Django 3.0.5 on 2020-04-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_hamburguesa_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='postings.Ingrediente'),
        ),
    ]
