# Generated by Django 3.0.5 on 2020-04-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_ingredienteenhamburguesa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredienteEnHamburguesa',
        ),
    ]
