# Generated by Django 3.0.5 on 2020-04-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0008_delete_ingredienteenhamburguesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='descripcion',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
