# Generated by Django 3.0.5 on 2020-05-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0011_auto_20200430_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
