# Generated by Django 3.0.5 on 2020-05-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0013_auto_20200501_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='hamburguesa_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='ingredient_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
