# Generated by Django 3.0.5 on 2020-05-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0014_auto_20200501_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamburguesa',
            old_name='hamburguesa_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='ingredient_id',
            new_name='id',
        ),
    ]
