# Generated by Django 3.0.5 on 2020-05-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0015_auto_20200502_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='imagen',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
