# Generated by Django 3.0.5 on 2020-05-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0016_auto_20200503_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
